### PR TITLE
Fixed a thing that can cause errors

### PR DESCRIPTION
**Pull request by NotANullPointer**
If you try a thing like
api.getStats(Stats.hdd);
api.getStats(Stats.cpu);
api.getStats(Stats.elo);
api.getStats(Stats.rank);
api.getStats(Stats.av);
api.getStats(Stats.adw);

It will return an error.

With this fix, the api will load the json once, then get all stats based on the loaded JSON.
I added a "refresh" method too, so the dev can refresh stats and get new one.

### CODE REVIEW

**Comment by itsfolf** [comment]
Hi @C0mm4nd, your fork is 1 commit behind the main one, wich is causing conflict, can you please update your fork?

**Comment by NotANullPointer** [comment]
thx for the updates

**Comment by itsfolf** [comment]
I had to revert it since there was compilation errors:
```[ERROR] /home/travis/build/OlympicCode/vHackAPI-Java/src/main/java/me/checkium/vhackapi/vHackAPI.java:[43,28] cannot find symbol

[ERROR] symbol:   variable json

[ERROR] location: class me.checkium.vhackapi.vHackAPI

[ERROR] /home/travis/build/OlympicCode/vHackAPI-Java/src/main/java/me/checkium/vhackapi/vHackAPI.java:[45,28] cannot find symbol

[ERROR] symbol:   variable json

**Comment by NotANullPointer** [comment]
Wait lemme fix

**Comment by NotANullPointer** [comment]
Ok, fixed. I forgot to change "return json...." to "return stats...."

**Comment by itsfolf** [comment]
How didn't your IDE warn you?

**Comment by NotANullPointer** [comment]
I wasn't on a IDE, I just changed 6 lines

**Comment by itsfolf** [comment]
You actually need to create a new pull request btw

**Comment by NotANullPointer** [comment]
k

**Pull request merged**
