### PR TITLE
Fixed a little thing

### PR DESCRIPTION
**Pull request by NotANullPointer**

### CODE REVIEW

**Comment by itsfolf** [comment]
Now you forgot the if, wtf?

**Comment by NotANullPointer** [comment]
wut

**Comment by itsfolf** [comment]
image
Wheres the if?

**Comment by NotANullPointer** [comment]
Fixed thought

**Comment by itsfolf** [comment]
Just waiting for the compile to check if it's everything ok

**Comment by NotANullPointer** [comment]
Finally it worked

**Comment by Qup42** [comment]
Is it possible that the methodes for refreshing the cache are missing in this commit?

**Comment by Qup42** [comment]
Then lets go

**Comment by NotANullPointer** [comment]
thx, sorry for the errors

**Pull request merged**
