### PR TITLE
Code cleanup and some fixes

### PR DESCRIPTION
**Pull request by angelbirth**
I made some cleanup and fix some logic in some functions

### CODE REVIEW

**Comment by itsfolf** [comment]
Is it propositally to have two methods to trojan transfer someone. One with multiple IPs one with only one. With names totally different?

**Comment by itsfolf** [comment]
@angelbirth Also, ingore the travis-ci error.

**Comment by angelbirth** [comment]
no, sorry, I thought I was gonna leave the "original" method for compatibility so that the examples still compiles without error. You can edit my method (or yours) if you want.

**Comment by itsfolf** [comment]
@angelbirth Can you fix the conflicts?

**Pull request merged**
